### ISSUE TITLE
translations: request to add links in README

### ISSUE THREAD

**Issue by time-river** [0xAX/asm#15]
Hey:
Long long age, I found your articles and thinks its good, so I translates these series to Chinese. 
[译文: Say hello to x64 Assembly [part 1]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-1/)
[译文: Say hello to x64 Assembly [part 2]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-2/)
[译文: Say hello to x64 Assembly [part 3]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-3/)
[译文: Say hello to x64 Assembly [part 4]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-4/)
[译文: Say hello to x64 Assembly [part 5]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-5/)
[译文: Say hello to x64 Assembly [part 6]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-6/)
[译文: Say hello to x64 Assembly [part 7]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-7/)
[译文: Say hello to x64 Assembly [part 8]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-8/)

Could you add those translation to your README ? :-) Just add the following code:

```
[译文: Say hello to x64 Assembly [part 1]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-1/)
[译文: Say hello to x64 Assembly [part 2]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-2/)
[译文: Say hello to x64 Assembly [part 3]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-3/)
[译文: Say hello to x64 Assembly [part 4]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-4/)
[译文: Say hello to x64 Assembly [part 5]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-5/)
[译文: Say hello to x64 Assembly [part 6]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-6/)
[译文: Say hello to x64 Assembly [part 7]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-7/)
[译文: Say hello to x64 Assembly [part 8]](https://vvl.me/2016/08/translation-Say-hello-to-x64-Assembly-part-8/)
```

**Comment by 0xAX** [comment]
Updated README.md, thank you @time-river!
