### ISSUE TITLE
Add new translation to README file

### ISSUE THREAD

**Issue by develoopeer** [0xAX/asm#39]
Hello @0xAX.
I made a fork with translation into Russian, and created a corresponding PR #38 to mention it in README.

Translation covers all 8 posts, and changes some typos. Also no references to the main repository were removed.
Could you mention it in your repo, for Russian readers?

**Comment by 0xAX** [comment]
Yes sure

**Comment by 0xAX** [comment]
merged :tada:

**Comment by develoopeer** [comment]
thanks
