### ISSUE TITLE
Ask about part 3 of say-hello-to-x64-assembly

### ISSUE THREAD

**Issue by okaprinarjaya** [0xAX/asm#7]
Hi,

My name is Oka. I very very beginner in assembly programming. I learn assembly through your articles at your website. 

I have some questions for part 3 http://0xax.blogspot.co.id/2014/09/say-hello-to-x64-assembly-part-3.html 

**1st question**

```asm
;; get argv[1]
pop rsi

;; convert argv[1] str to int
call  str_to_int
```
We are popping up argv[1] from the stack. But why at `str_to_int` function you XOR'ing value at `rax` register ? How value at `rsi` register get copied to `rax` register ? . In my very beginner understanding, when we do `pop rsi` , the value from stack will copied to `rsi` register. From my beginner view, value at `rsi` will become parameter passed to `str_to_int`, but  it looks value at `rsi` register not touched. 

**2nd question**
When  `next` function called ? 

**3rd Question**
Why executing `ret` instruction must be wrapped in a function `return_str` ? Why not just type `ret`

Thank You :)

**Comment by 0xAX** [comment]
Hello @okaprinarjaya,

> We are popping up argv[1] from the stack. But why at str_to_int function you XOR'ing value at rax register ? How value at rsi register get copied to rax register ?.

Why did you decide that `%rsi` copied to `%rax`? Here we clear `%rax` to return result in there as result of `str_to_int`. And `%rsi` just contain value of `argv[1]`.

>  When next function called ?

It is not function, just a label, see `jmp` instruction in the end:

```assembly
next:
	    cmp [rsi], byte 0
	    je return_str
	    mov bl, [rsi]
            sub bl, 48
	    mul rcx
	    add rax, rbx
	    inc rsi
	    jmp next
```

>  Why executing ret instruction must be wrapped in a function return_str ? Why not just type ret

It is not function, but label too. In this case we may jump on this label, see:

```assembly
je return_str
```

Hope this helps.

**Comment by okaprinarjaya** [comment]
Hi @0xAX ,

Thank you for your help and attention

**2nd question**
I just realized now that labels is "automatically" executed. Before your answer, my brain treat label like a function definition and call (not executed when not get called)

**3rd question**
mmmm...it's mean `jne` cannot use `ret` as operand directly, right? So we can't do this `jne ret`

**1st question**
Ok..so `next` label is automatically executed after `str_to_int` executed

**Comment by okaprinarjaya** [comment]
My next question,

```asm
;; Print number
;;
print:
    ;;;; calculate number length
    mov rax, 1
    mul r12
    mov r12, 8
    mul r12
    mov rdx, rax
    ;;;;
```

I understand putting value to `rdx` register is for syscall's sys_write() 3rd argument. But why not just use plain incremented `r12` directly? Because at label `int_to_str` you incrementing `r12`
why `r12` not ready to use? 

Thank you

**Comment by 0xAX** [comment]
>  mmmm...it's mean jne cannot use ret as operand directly, right? So we can't do this jne ret

`jne`, `je` and other instructions: **jump** if something.

> Because at label int_to_str you incrementing r12 why r12 not ready to use?

Actually yes, we can. Didn't think about this when wrote this code

**Comment by okaprinarjaya** [comment]
Thank you very much @0xAX :+1:
